name: Schedule delete table content
on:
  schedule:
    # 毎日12:25に実行
    - cron: '25 3 * * *'
jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 3  # タイムアウトを3分に設定
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install tsx
        run: npm install -D tsx

      - name: Run batch script to delete data
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        # run: npx ts-node --esm ./batch/index.ts
        run: npx tsx ./batch/index.ts